service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: product
          method: get
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
